#!c:/perl/bin/perl.exe -w
#Perl Script to trigger lights on different port than main web server.
use strict;
use LWP::Simple;
use CGI qw(:standard);

my $aQuery = CGI->new();
my $anAction = $aQuery->param('action');
my $aUrl = "#GarageUrl#${anAction}";
my $response = get $aUrl;
print "Content-Type: application/json; charset=utf-8\n\n${response}";
